### ISSUE TITLE
行頭の全角スペースが削除される

### ISSUE THREAD

**Issue by azyobuzin** [kb10uy/shortstoryserver2#3]
PHP 実装では削除されてなかったけれど、 Playground の WASM 実装では削除される。

**Comment by kb10uy** [comment]
たぶん `trim()` が Unicode 考慮されるようになったせい。これどうしようか。

**Comment by kb10uy** [comment]
https://github.com/kb10uy/shortstoryserver2/commit/58615e6bf032968939cea645a3c9809ea5f4ada6
どうなんだろうこれは

**Comment by kb10uy** [comment]
とりあえず残すようにはできたので close します
